//action Types for Holidays table
export const ADD_HOLIDAY = 'ADD_HOLIDAY';
export const HOLIDAY_FAILED = 'HOLIDAY_FAILED';
export const ADD_HOLIDAYS = 'ADD_HOLIDAYS';
export const DELETE_HOLIDAY = 'DELETE_HOLIDAY';
//action types for country table
export const ADD_COUNTRY = 'ADD_COUNTRY';
export const COUNTRY_FAILED = 'COUNTRY_FAILED';
export const ADD_COUNTRIES = 'ADD_COUNTRIES';
export const DELETE_COUNTRY = 'DELETE_COUNTRY';
//action types for state table
export const ADD_STATE = 'ADD_STATE';
export const STATE_FAILED = 'STATE_FAILED';
export const ADD_STATES = 'ADD_STATES';
export const DELETE_STATE = 'DELETE_STATE';
//action types for city table
export const ADD_CITY = 'ADD_CITY';
export const CITY_FAILED = 'CITY_FAILED';
export const ADD_CITIES = 'ADD_CITIES';
export const DELETE_CITY = 'DELETE_CITY';
//action types for formula notes table
export const ADD_NOTE = 'ADD_NOTE';
export const NOTE_FAILED = 'NOTE_FAILED';
export const ADD_NOTES = 'ADD_NOTES';
export const DELETE_NOTE = 'DELETE_NOTE';
//action types for concerns table
export const ADD_CQ = 'ADD_CQ';
export const CQ_FAILED = 'CQ_FAILED';
export const ADD_CQS = 'ADD_CQS';
export const DELETE_CQ = 'DELETE_CQ';
//action types for gregorian month table
export const ADD_GM = 'ADD_GM';
export const GM_FAILED = 'GM_FAILED';
export const ADD_GMS = 'ADD_GMS';
export const DELETE_GM = 'DELETE_GM';
//action types for gregorian month special table
export const ADD_GM_S = 'ADD_GM_S';
export const GMS_FAILED = 'GMS_FAILED';
export const ADD_GMSS = 'ADD_GMSS';
export const DELETE_GMS = 'DELETE_GMS';
//action types for gregorian month nth kday table
export const ADD_GNK = 'ADD_GNK';
export const GNK_FAILED = 'GNK_FAILED';
export const ADD_GNKS = 'ADD_GNKS';
export const DELETE_GNK = 'DELETE_GNK';
//action types for GKM table
export const ADD_GKM = 'ADD_GKM';
export const GKM_FAILED = 'GKM_FAILED';
export const ADD_GKMS = 'ADD_GKMS';
export const DELETE_GKM = 'DELETE_GKM';
